### PR TITLE
Readme improvements

### PR DESCRIPTION
**Pull request by spilth**
I updated the README to put the installation directions right in a user's face.

Also using `bundle --path vendor/bundle` to try and not screw with system Ruby as much as possible.

### CODE REVIEW

**Comment by mikfreedman** [comment]
+1

**Comment by hiremaga** [comment]
Thanks @spilth!

I recall going to some lengths to avoid a full XCode install and instead installing just the CLI tools with xcode-select. Is the change back to a full XCode install necessary?

**Comment by spilth** [comment]
When I tried to install sprout-vim it complained that it needed XCode.

**Comment by hiremaga** [comment]
Ah :) we've gone back and forth about how whether to use the cask or
formula for macvim, the latter needs all of XCode. The only remaining
dependency.

+1 to this PR @wendorf

**Comment by mikfreedman** [comment]
+1

**Comment by hiremaga** [comment]
@wendorf I took a liberty... ;)

**Comment by aramprice** [comment]
@hiremaga regarding full Xcode install - I have repeatedly had problems successfully running `gem install nokogiri` on a fresh El Capitain machine **until** a full version of Xcode is installed *via the App Store*. Using a `.dmg` based install or using the CLI tools did not work.

I believe the `sprout-vim` issue is because that cookbook compiles macvim in order to include lua support. @luan would have more context.

**Comment by hiremaga** [comment]
@aramprice I wonder if it's the version of Xcode rather than whether it's
via one source or another. I have a theory that nokogiri and Xcode versions
play a cat and mouse game, so every time a new version of Xcode is out a
new version of nokogiri is needed for it to compile correctly.

And, I think you're right about sprout-vim and lua support. We'd be able to
able to stop compiling the macvim if somebody (@luan, koff koff) maintained
a binary tap with a lua friendly version of macvim.

**Comment by aramprice** [comment]
FWIW I had trouble again trying to install nokogiri this time with the latest Xcode, and latest nokogir on El Capitan, using system ruby, latest bundler and latest ruby gems code.

On a different machine with the same configuration nokogiri compiled fine.

We worked around this by dropping `foodcritic` - it is the only gem in our sprout-exemplar that requires nokogiri :-/

**Pull request merged**
