### PR TITLE
Update cookbook for macOS High Sierra

### PR DESCRIPTION
**Pull request by aramprice**
* drops support for macOS < 10.13
* stop locking gems for compatibility with macOS's EOL'd ruby

### CODE REVIEW

**Comment by aramprice** [comment]
Build is failing because of https://github.com/pivotal-sprout/sprout-base/issues/16

**Comment by tgaff** [comment]
https://github.com/pivotal-sprout/sprout-base/pull/18 was merged (appears to be a replacement for sprout-base#16).  But this still failed for me on a new MBP w/ 10.13.4
Might be able to re-test though.

**Comment by aramprice** [comment]
Build is still failing because the cookbooks and gems haven't been updated with the upstream changes (`./sprout update` from within `sprout-wrap`).

Updating the PR with those changes.

**Comment by cunnie** [comment]
Looks good to me! I should caution you that my sprout-fu is very weak these days — the last two teams I've been on use an alternate (`construct`), so I haven't been keeping abreast of sprout developments.

**Pull request merged**
